# Generated by Django 3.2.7 on 2024-04-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
                ('team1_name', models.CharField(max_length=100)),
                ('team2_name', models.CharField(max_length=100)),
                ('team1_possession_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('team2_possession_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
