# Generated by Django 3.2.7 on 2024-04-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20240418_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name': 'Goal', 'verbose_name_plural': 'Goals'},
        ),
        migrations.AlterField(
            model_name='goal',
            name='team1_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goal',
            name='team2_name',
            field=models.CharField(max_length=100),
        ),
    ]
