# Generated by Django 3.2.7 on 2024-04-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20240418_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={},
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='FG',
            new_name='team1_FG',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='PG',
            new_name='team1_PG',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='total',
            new_name='team2_FG',
        ),
        migrations.AddField(
            model_name='goal',
            name='team2_PG',
            field=models.IntegerField(default=0),
        ),
    ]
