# Generated by Django 3.2.7 on 2024-04-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20240419_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='team1_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='team2_total',
            field=models.IntegerField(default=0),
        ),
    ]
