# Generated by Django 3.2.7 on 2024-04-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20240419_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
                ('team1_name', models.CharField(max_length=100)),
                ('team2_name', models.CharField(max_length=100)),
                ('circle_team1', models.IntegerField(default=0)),
                ('circle_team2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
                ('team1_name', models.CharField(max_length=100)),
                ('team2_name', models.CharField(max_length=100)),
                ('shots_team1', models.IntegerField(default=0)),
                ('shots_team2', models.IntegerField(default=0)),
            ],
        ),
    ]
