# Generated by Django 3.2.7 on 2024-04-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_circle_shots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='circle_team1',
            new_name='team1_circle',
        ),
        migrations.RenameField(
            model_name='circle',
            old_name='circle_team2',
            new_name='team2_circle',
        ),
        migrations.RenameField(
            model_name='shots',
            old_name='shots_team1',
            new_name='team1_shots',
        ),
        migrations.RenameField(
            model_name='shots',
            old_name='shots_team2',
            new_name='team2_shots',
        ),
        migrations.AlterField(
            model_name='circle',
            name='match_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='shots',
            name='match_number',
            field=models.IntegerField(unique=True),
        ),
    ]
