# Generated by Django 3.2.7 on 2024-05-02 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_team_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_type', models.CharField(max_length=100)),
                ('injury_details', models.TextField()),
                ('body_part', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('date_reported', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(max_length=100)),
                ('treatment_date', models.DateField()),
                ('notes', models.TextField()),
                ('injury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.injury')),
            ],
        ),
        migrations.AddField(
            model_name='injury',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.player'),
        ),
    ]
