# Generated by Django 3.2.7 on 2024-05-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20240502_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('pattern_name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
        ),
    ]
