# Generated by Django 3.2.7 on 2024-05-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_teampattern'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamPattern',
        ),
        migrations.AddField(
            model_name='goal',
            name='team1_result',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='team2_result',
            field=models.IntegerField(default=0),
        ),
    ]
