# Generated by Django 3.2.7 on 2024-05-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_auto_20240507_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueBlazerzData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
                ('possession_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('circle_count', models.IntegerField()),
                ('shots_count', models.IntegerField()),
                ('field_goal', models.IntegerField()),
                ('penalty_goal', models.IntegerField()),
                ('penalty_corners', models.IntegerField()),
                ('penalty_strokes', models.IntegerField()),
                ('result', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GreenGriffinzData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
                ('possession_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('circle_count', models.IntegerField()),
                ('shots_count', models.IntegerField()),
                ('field_goal', models.IntegerField()),
                ('penalty_goal', models.IntegerField()),
                ('penalty_corners', models.IntegerField()),
                ('penalty_strokes', models.IntegerField()),
                ('result', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedRufiianzData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
                ('possession_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('circle_count', models.IntegerField()),
                ('shots_count', models.IntegerField()),
                ('field_goal', models.IntegerField()),
                ('penalty_goal', models.IntegerField()),
                ('penalty_corners', models.IntegerField()),
                ('penalty_strokes', models.IntegerField()),
                ('result', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VioletWhalezData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
                ('possession_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('circle_count', models.IntegerField()),
                ('shots_count', models.IntegerField()),
                ('field_goal', models.IntegerField()),
                ('penalty_goal', models.IntegerField()),
                ('penalty_corners', models.IntegerField()),
                ('penalty_strokes', models.IntegerField()),
                ('result', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhiteWarriorszData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
                ('possession_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('circle_count', models.IntegerField()),
                ('shots_count', models.IntegerField()),
                ('field_goal', models.IntegerField()),
                ('penalty_goal', models.IntegerField()),
                ('penalty_corners', models.IntegerField()),
                ('penalty_strokes', models.IntegerField()),
                ('result', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YellowYakzData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
                ('possession_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('circle_count', models.IntegerField()),
                ('shots_count', models.IntegerField()),
                ('field_goal', models.IntegerField()),
                ('penalty_goal', models.IntegerField()),
                ('penalty_corners', models.IntegerField()),
                ('penalty_strokes', models.IntegerField()),
                ('result', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
