# Generated by Django 3.2.7 on 2024-05-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_blueblazerzdata_greengriffinzdata_redrufiianzdata_violetwhalezdata_whitewarriorszdata_yellowyakzdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
