# Generated by Django 3.2.7 on 2024-05-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_auto_20240511_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=10)),
                ('card', models.CharField(max_length=10)),
                ('goals', models.IntegerField()),
                ('dribbling', models.IntegerField()),
                ('scoop', models.IntegerField()),
                ('tackling', models.IntegerField()),
                ('hit', models.IntegerField()),
                ('sweep', models.IntegerField()),
                ('air_tapping', models.IntegerField()),
                ('gk_save_count', models.IntegerField()),
                ('gk_recovery_time', models.FloatField()),
            ],
        ),
    ]
